import type { DesktopAPI } from './types'

export function createDesktopAPI(
  partialBridge: Partial<DesktopAPI> | undefined,
  fallback: DesktopAPI,
): DesktopAPI {
  return {
    getVersion: partialBridge?.getVersion ?? fallback.getVersion,
    getPlatformInfo: partialBridge?.getPlatformInfo ?? fallback.getPlatformInfo,
    getRuntimeConfig: partialBridge?.getRuntimeConfig ?? fallback.getRuntimeConfig,
    onNavigate: partialBridge?.onNavigate ?? fallback.onNavigate,
    openExternal: partialBridge?.openExternal ?? fallback.openExternal,
    selectImages: partialBridge?.selectImages ?? fallback.selectImages,
    selectPdf: partialBridge?.selectPdf ?? fallback.selectPdf,
    registerScannerImage: partialBridge?.registerScannerImage ?? fallback.registerScannerImage,
    enhanceImage: partialBridge?.enhanceImage ?? fallback.enhanceImage,
    processCrops: partialBridge?.processCrops ?? fallback.processCrops,
    eraseImage: partialBridge?.eraseImage ?? fallback.eraseImage,
    splitQuestions: partialBridge?.splitQuestions ?? fallback.splitQuestions,
    agentExplain: partialBridge?.agentExplain ?? fallback.agentExplain,
    agentAnalogy: partialBridge?.agentAnalogy ?? fallback.agentAnalogy,
    paperProcess: partialBridge?.paperProcess ?? fallback.paperProcess,
    getCaptcha: partialBridge?.getCaptcha ?? fallback.getCaptcha,
    login: partialBridge?.login ?? fallback.login,
    logout: partialBridge?.logout ?? fallback.logout,
    changePassword: partialBridge?.changePassword ?? fallback.changePassword,
    getAuthSession: partialBridge?.getAuthSession ?? fallback.getAuthSession,
    onAuthStateChanged: partialBridge?.onAuthStateChanged ?? fallback.onAuthStateChanged,
    buildPagePreview: partialBridge?.buildPagePreview ?? fallback.buildPagePreview,
    savePage: partialBridge?.savePage ?? fallback.savePage,
    printPage: partialBridge?.printPage ?? fallback.printPage,
    printSvgPages: partialBridge?.printSvgPages ?? fallback.printSvgPages,
    saveSvgPages: partialBridge?.saveSvgPages ?? fallback.saveSvgPages,
    listBookEntries: partialBridge?.listBookEntries ?? fallback.listBookEntries,
    addBookEntries: partialBridge?.addBookEntries ?? fallback.addBookEntries,
    removeBookEntry: partialBridge?.removeBookEntry ?? fallback.removeBookEntry,
    updateBookEntry: partialBridge?.updateBookEntry ?? fallback.updateBookEntry,
    addBookPractice: partialBridge?.addBookPractice ?? fallback.addBookPractice,
    buildBookPreview: partialBridge?.buildBookPreview ?? fallback.buildBookPreview,
    printBook: partialBridge?.printBook ?? fallback.printBook,
    bumpBookPractice: partialBridge?.bumpBookPractice ?? fallback.bumpBookPractice,
    randomBookEntries: partialBridge?.randomBookEntries ?? fallback.randomBookEntries,
    openLogDirectory: partialBridge?.openLogDirectory ?? fallback.openLogDirectory,
    selectDirectory: partialBridge?.selectDirectory ?? fallback.selectDirectory,
    listPrinters: partialBridge?.listPrinters ?? fallback.listPrinters,
    getAbility: partialBridge?.getAbility ?? fallback.getAbility,
    getConfig: partialBridge?.getConfig ?? fallback.getConfig,
    setConfig: partialBridge?.setConfig ?? fallback.setConfig,
    getUpdateState: partialBridge?.getUpdateState ?? fallback.getUpdateState,
    checkForUpdates: partialBridge?.checkForUpdates ?? fallback.checkForUpdates,
    downloadUpdate: partialBridge?.downloadUpdate ?? fallback.downloadUpdate,
    installUpdate: partialBridge?.installUpdate ?? fallback.installUpdate,
    onUpdateStateChanged: partialBridge?.onUpdateStateChanged ?? fallback.onUpdateStateChanged,
  }
}
